### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by murithigeo** [s3xysteak/vite-plugin-cesium-build#12]
I'm getting a ReferenceError: module is not defined on a pure create-svelte install.

>[vite] Error when evaluating SSR module /node_modules/.vite-plugin-externals/cesium.js:
|- ReferenceError: module is not defined
    at C:\Users\users\Desktop\projects\coveragejsonTestBed\node_modules\.vite-plugin-externals\cesium.js:1:8

**Comment by s3xysteak** [comment]
I will check it later. There is a [svelte exapmle](https://github.com/s3xysteak/vite-plugin-cesium-build/tree/main/examples/svelte), which is also created by `create-svelte`. I just try it and it works correctly. I think maybe there are some break changes in create-svelte.

**Comment by murithigeo** [comment]
I've checked and it happens when the module is SSRd.

**Comment by s3xysteak** [comment]
I add an example for svelte-kit: https://github.com/s3xysteak/vite-plugin-cesium-build/tree/main/examples/svelte-kit
It looks good to me. If you still have any problem, feel free to reopen the issue!
