### ISSUE TITLE
cesium1.96时报错

### ISSUE THREAD

**Issue by zhaozg117** [s3xysteak/vite-plugin-cesium-build#13]
![image](https://github.com/user-attachments/assets/b9b08c9f-6728-4818-b110-56e4a16dca21)

**Comment by s3xysteak** [comment]
`Cesium@1.96` just not support to do that. Refer to the changes of `Cesium@1.97`:

> Export asset files such as CSS in package.json, allowing bundlers to import without additional configuration. https://github.com/CesiumGS/cesium/pull/9212

That's why I don't set option `css` to true by default.
