### ISSUE TITLE
cesium rendering issue

### ISSUE THREAD

**Issue by lovelindhoni** [s3xysteak/vite-plugin-cesium-build#17]
Hey @s3xysteak , thank you for your work!

I scaffolded a new Svelte-Vite project and integrated Cesium using the plugin. However, I'm encountering an issue where a large, white-spotted circle renders over the OSM buildings.

![image](https://github.com/user-attachments/assets/6563adf0-fa1f-489d-9864-afeeac30b9c4)

To make troubleshooting easier, I've created a minimal repro repository that replicates the issue. It simply loads the cesium buildings with some configurations 
https://github.com/lovelindhoni/cesium-white-circle-repro
run: `pnpm i && pnpm run dev`

Here is the `App.svelte` file on that repo:
```svelte
<script lang="ts">
  import "cesium/Build/Cesium/Widgets/widgets.css";
  import * as Cesium from "cesium";

  let container: null | Element = $state(null);

  $effect(() => {
    if (container) {
      const viewer = new Cesium.Viewer("cesiumContainer", {
        baseLayer: Cesium.ImageryLayer.fromProviderAsync(
          Cesium.TileMapServiceImageryProvider.fromUrl(
            Cesium.buildModuleUrl("Assets/Textures/NaturalEarthII"),
          ),
        ),
        baseLayerPicker: false,
        geocoder: false,
      });
      viewer.scene.skyAtmosphere.show = true;

      const latitude = 23.0225;
      const longitude = 72.5714;
      const altitude = 100; // Altitude in meters
      const heading = 0;
      const pitch = -20.0;
      const roll = 0.0;
      const orientation = {
        heading: Cesium.Math.toRadians(heading),
        pitch: Cesium.Math.toRadians(pitch),
        roll: Cesium.Math.toRadians(roll),
      };
      const position = Cesium.Cartesian3.fromDegrees(
        longitude,
        latitude,
        altitude,
      );
      viewer.scene.camera.setView({
        destination: position,
        orientation,
      });
      (async () => {
        const buildingTileset = await Cesium.createOsmBuildingsAsync();
        viewer.scene.primitives.add(buildingTileset);
      })();
      viewer.scene.requestRender();
    }
  });
</script>

<div bind:this={container} class="cesiumContainer"></div>

<style>
  .cesiumContainer {
    width: 100dvw;
    height: 100dvh;
  }
</style>
```

**Comment by s3xysteak** [comment]
It can be reproduced in [sandcastle](https://sandcastle.cesium.com/#c=fVRdb9owFP0rFk+JxJwQ2lUrHxqje5laVWrZnngxzoVYODbzdWBs6n+f7ZBQaClCIvfec8/9OoRrhZZsBezAkBFRsCNTQFGV9FfwRfMOD/ZUK8uEAjPvxIO5mqs6hyIHBRTX+4ktNW4KMM4q9M6RWVNBgPJQRDIrbJWDi2R9mmbZ9aANabVqYjcZvb7pXbUxJtu0XpoOSJKQSeMSipRgwWADLoDlQq0cNm0JNsLywnk+ZSk9eo2W0sNeubQR4Ia0QisX+TdXpOG7bZbywGxBrX5yXqYwOoTjrseGOpeQIVjjfOVLMB/zqJdj9xrFoaNDypQZ656Y6tOl0eUdrAwARp663WMo1Cw8GM0aneHvd3I9zkowjCJYf/QoTJ4DWqHCMm7bJgLTqzX5Tj1bxHCvOIliMhrXi6ubX1RC+gXNhATH7mZgOyZsMwk3wCw8YvntgMOJ54k8JSEnLW6MKF0LW0DK8jw6I/YJL3H0ZjAsWK53D2xDQbGFhPyoygu4nJm1AsQgjf5l3DIc/nvLumQSP6BF8dcL+Cr98vkyqGR/RFmVdwItU9zj+2l6DpdiVdjTf+pzpe6996P5z/s93QKXmq8pr4xxl52JEo5q+1FJJ7U7d6dabe4hSM3XD0YI/ZxNoyzNrrqk1+uS8Jt1Seq+cfye4gz8rpzAnkDl7h0TDzrdzhDtXsLYc/vPV1FutLGkMjKiNLFQbpyeAZNFxddgKUesZULIMHmdOszFloh89M6Li3DJEF1kWUn57E4y74yHicO/SZU67OtxC0ayvYcVvfF97aSUDhNnvp9ptZYLZs6Y/wM) so I think it may be a bug of CesiumJS.

**Comment by lovelindhoni** [comment]
Yeah, that explains
