### ISSUE TITLE
Cesium Engine compatibility

### ISSUE THREAD

**Issue by jfayot** [s3xysteak/vite-plugin-cesium-build#6]
Hi s3xysteak !
Thanks for the plugin. That works well !

I was wondering if this would be a lot of work to get it compatible also with the @cesium/engine only ?

What do you think ?

**Comment by s3xysteak** [comment]
I haven't heard of @cesium/engine before, so it might take some time. It would be helpful if you could provide some documents that describe the differences between `@cesium/engine` and `cesium`, or a sample repository that uses `@cesium/engine`.

**Comment by jfayot** [comment]
Hi again,
have a look [here](https://github.com/jfayot/demo-cesium-widget) for a sample repo
Thanks for your support !

**Comment by jfayot** [comment]
BTW, you will get some more information on @cesium/engine [here](https://community.cesium.com/t/cesium-engine-and-cesium-widgets-are-now-available-for-testing/20898)...

**Comment by s3xysteak** [comment]
See line2. Use it just like examples in `README`.
```diff
import { defineConfig } from 'vite'
- import cesium from 'vite-plugin-cesium-build'
+ import cesium from 'vite-plugin-cesium-build/engine'

export default defineConfig({
  plugins: [
    //...
    cesium()
  ]
})

```
